== To The Reader

Whether you are a friend to Truth, or an enemy,
the things declared in this book may be of service to you,
if you will but read them meekly and soberly;
for they are given forth from that innocent Life that the serpent ever makes war against.
Therefore, when you enter upon it, and undertake to read it,
do so in the dread and fear of the Lord God, sinking into lowliness,
and feeling after God`'s Witness in your own conscience,
so that you may read and truly understand.
And as you keep to the Spirit`'s manifestation in yourself, and read in that,
you will feel when your condition is reached and spoken to.
Then keep quiet and be still, and do not let anger or envy arise in your heart,
which the serpent sometimes will provoke you to; for if you give way to this,
and allow it to arise, it will prevent you from profiting.
Read therefore in meekness, and receive this in that same love from which it is declared.
Then you will feel the weight of the truth, and reap advantage and profit by it,
and you will feel how far you have come to witness redemption by the power of Christ,
or where the serpent yet holds you, and to what you are still in bondage.
And as your chains are seen in His Light, then turn to the Light, and deny all else,
so that whatever it is will be judged, crucified on the cross, and consumed in the fire.
_Through this gate, the flaming sword, you must come,_
or you will be excluded from the paradise of God, and kept from the Tree of life.
But as you yield to the Lord and come to know His work, He will judge your lusts,
crucify your life, and destroy the body of sin;
and so through death He will bring forth a new Life in which you
will feel a perfect change wrought from the earthly to the heavenly.
Here you will enjoy the Lord and His presence, power, and goodness,
and at last sit quietly in joy, peace and blessing.

[.signed-section-signature]
William Smith

[.signed-section-context-close]
First Month, 1661
