== Chapter 1. The State of Man in the Creation

The Lord God of life and power, who is from everlasting to everlasting,
according to the good pleasure of His own will, and after the counsel of His own heart,
brought forth a pure creation in His wisdom.
By His eternal living Word, He divided and separated the matter, which, in the chaos,
was in a heap of confusion.
Whatever He commanded by His Word came to pass; and just as He said it should be,
so it was done.
In His wisdom a pure creation was finished.

When He had stretched forth the heavens, and placed the lights in them,
and when He had laid the foundation of the earth,
and brought forth the herbs and trees therein, and when He had divided the waters,
and the fish multiplied in them, when the birds of the heavens took flight in the air,
and four-footed beasts and creeping things had their way upon the earth;
then the eternal Word (in wisdom) made man in His own image,
and breathed into him the breath of Life, so that he became a living soul.
The Lord God filled him with wisdom and understanding,
and gave him dominion over all the works of His hands,
so that he ruled over all in the wisdom of God.
Man then stood in God`'s wisdom, and received counsel, and had his way in the holy Life.
He walked in the paradise of pleasure, fed upon the Tree of Life,
and lived in a still and peaceful communion with his God,
where his living soul abode in God`'s living virtue,
with the breath of His Life always reaching unto it.
So man lived in a pure oneness with the God that made him,
and the image of the Holy Life was upon him.
He abode in the power, wisdom, and strength of God,
and bore His image in righteousness and true holiness, without any mixture.
All things stood clear and clean in the proper separation in which they were created,
and there was no mixture to defile.

Then did Wisdom behold His work, and lo, it was very good in His sight.
He had great pleasure and delight therein, and His mercy, love, goodness,
and tenderness was towards it, and His blessing and peace was upon it.
Man enjoyed the living presence of his Maker, and so partook of His love, mercy,
blessing and peace.
He had free access to the well-spring of Life,
and there was nothing that stood in his way.
So the breath of Life was continually breathed forth, and in it the soul lived,
being in perfect unity with it.
This was not something from without,
but was rather of the pure operation of God`'s power and wisdom within.
Yes, God formed an earthly body and brought forth a visible creation,
so that He might fill it with His heavenly treasure--with His own Holy Life,
which He breathed into it.
Thus the Creator brought forth man in His own image,
and there was no mixture in his life and being.
The earthly body was made a compound vessel,
prepared and formed in the wisdom of God to be a
vessel for the incorruptible image of Life.
In the beginning, the Life of God had free course in man,
and filled him with His heavenly being,
and there was no mixture of the earthly in his life and being.

This was the man that was created according to God in righteousness and true holiness,
and who bore His image in perfect glory.
The body was prepared as a vessel fit for the use of the One who made it,
that He might fill it with His pure and holy Life.
Here man stood in obedience to the Father of spirits, who had made him a spiritual, holy,
and righteous man, and fed him with spiritual, holy food.
Thus, man at first had no will or desire after any created thing,
but stood in the eternal will, and ruled over all the creatures.
His one desire was to enjoy the holy Life in which he was generated and brought forth.
And whatever he desired to partake of in the Life was ministered
to him according to the good pleasure of the Creator;
for He lived in the pure enjoyment of the eternal Being,
in Whom he was daily comforted and continually satisfied.
In this state there was no sin or evil committed by him.
No curse could reach him; no death was upon him, no grave did hold him,
nor could any wrath go forth against him.
In mercy he lived, and mercy was his portion.
Man`'s delight was his Maker, and with Him he walked day and night,
enjoying true liberty in paradise, and free access to the Tree of Life.

So man was created in righteousness, served God in righteousness,
and lived in the Life of righteousness, knowing no mixture of any unrighteous thing.
He was created in the wisdom of God, and bore the image of God,
drawing the breath of Life from the holy Fountain.
He stood in the eternal essence of the divine nature, bringing forth the works of God;
and God rested from all the works that He had made.
