== Chapter II. The State of Man in the Degeneration

When the pure creation was finished in the eternal power and wisdom,
it rested in the holy order of Life,
and was in pure harmony and oneness with the Creator;
and there it should have remained--in the holy order--and should never
have been moved except in and by the power and wisdom of Life.
But there was a part of creation which did not keep in its place or station,^
footnote:[Jude 1:6]
but instead moved out of the wisdom, broke the holy order,
and aspired towards an equality with the Holy Essence.
For this reason it was cast down by the power,
and driven into the lowest parts of the creation,
and there it was given its place and habitation at the furthest distance from God.
Indeed, the Lord`'s anger was kindled against it, and He drove it down in His anger,
and His wrath abides upon it,
and it has been sealed in the anger and wrath without recovery.
This is the place assigned to that part of creation which did not keep in the holy order,
but aspired to be equal with the creating power.^
footnote:[Isaiah 14:13-15]
His name is the serpent, the devil, and his place is hell, the bottomless pit,
where the Almighty God manifests wrath without ceasing.

When this aspiring part of creation was cast down into the lowest parts,
it became beastly, earthly, sensual and devilish,
and was more subtle than any beast of the field.
Having lost his place in the pure creation,
and being cast down into separation from God (where
wrath or enmity is experienced without ceasing),
he then labored with his subtlety to draw out of
order that which still kept its station and order;
that is,
_he sought to beget a motion in man that was outside of the moving of God`'s power._

Now the Lord God had given a command unto man in the day that He placed him in paradise.
He charged him: "`Eat not of the tree of the knowledge of good and evil,
for in the day that you eat of it you shall surely die.`"^
footnote:[Genesis 2:17]
Knowing this, the serpent tempted the woman, because she was nearest unto man,
having been given unto him as a companion.
In subtlety he tempted her to eat of the fruit of the tree which God had forbidden,
saying, "`Has God indeed said,
'`You shall not eat of every tree of the garden?`' And the woman said to the serpent,
'`We may eat the fruit of the trees of the garden;
but of the fruit of the tree which is in the midst of the garden, God has said,
'`You shall not eat it, nor shall you touch it,
lest you die.`' Then the serpent said to the woman, '`You will surely not die.
For God knows that in the day you eat of it your eyes will be opened,
and you will be like God, knowing good and evil.`'`"^
footnote:[Genesis 3:1-5]

And when the serpent had gained entrance in the woman with this temptation,
and had drawn her mind to look upon it, she then saw that the tree was good for food,
pleasant to the eyes, and desirable to make one wise.
She took it and ate, and gave also to her husband, and he ate.
And thus, through the weaker part of creation, he thereby reached to the stronger,
and so entered and prevailed.
Then, alas, _the creation moved out of the power, and contrary to the power;_
and so the power of God (in which it should have remained and rested) was transgressed.
Thus creation went out of the pure order,
and man fell from the power and wisdom of the Creator,
by listening to the voice of the deceiver,
and transgressing against the God of his Life.

In this way man became a "`degenerate plant of an alien vine,`"^
footnote:[Jeremiah 2:21]
and lost his authority over the creation.
Having become subject to the serpent`'s subtlety,
he was driven out of paradise and into the earth,
where he became corrupted and defiled among the mixture of fallen earthly properties.
In a moment, all the faculties and properties of man changed,
and he was immediately turned from the image of the heavenly into the image of the earthly.
Thus he became an earthly man, with an earthly, carnal mind that was enmity with God,
and an earthly wisdom that was sensual and demonic,
in which the serpent stood exalted and had dominion over man.
And so the pure creation, which formerly stood in the mercy and love of the Creator,
was lost and brought into bondage, having fallen into dark mixtures;
and there it began to groan and travail with birth pangs.
And the serpent worked deceitfully in this mixture,
so that man became the subject of wrath and a curse, with death overshadowing him,
and hell inclosing him, chained to torment, anguish, pain, and fear.

So man lost the heavenly image in which he was created,
and an earthly image of the serpent`'s forming came upon him.
The world entered into his heart,
and in the world the serpent seated himself and exercised his power,
and became the god of this world.
And then the Tree of Life was guarded with Cherubim and a flaming sword,
and whichever way man turned (by the craftiness of the serpent)
to seek after and taste the Tree of Life,
the flaming sword turned and met him there.

But then the compassion of the Eternal Mercy moved, and His love opened,
and a Seed was appointed that would bruise the serpent`'s Head,
and recover man again out of the dark mixture where wrath is known,
and restore him to the love and mercy which were formerly his portion.
However,
the mind that had gone into the earth could see no beauty or comeliness in this Seed,
that it should desire after it or love its appearing,
but rather has remained at enmity against it.
For an earthly image is most desirable to an earthly mind,
and appears to it to be most beautiful.

Thus man has fallen and become degenerate,
and the earth has become his habitation and dwelling place.
Here he has an image from the begetting of the serpent,
and takes his nourishment from the old creation.
