== Chapter IV. The Way and Works of Man in the Separation

Having lost the power and wisdom in which he was created,
and in which he once ruled over the creatures,
and having been drawn downwards by the strength of deception,
man is now degenerated from the way of holiness and the works of righteousness,
and is led in the paths of darkness.
Here he has his course in the visible part of the creation,
and in the defiled way of his own inventions, which is broad and leads to destruction.
Here he wills and he runs, with the serpent hastening him on speedily,
_lest at any time he should stand still and consider the evil of his way and turn from it._
And so he is led further into separation from God, and drawn into the crooked path,
and a delight is begotten to walk therein,
being seduced by the various objects and appearances that the serpent presents to him.
Yes, he now finds his purpose, love, and delight wholly in these things,
so that he loves his pleasures and profits far more than God.
And the work of the serpent is to make this seem right to him,
drawing a deceitful cover over all such things,
so that men remain blind and do not see things as they are in the light.
Hence the drunkard says, "`My way is love to my friends;`" and the covetous man says,
"`My way is providence and prudence;`" and the proud man says,
"`My way is fashionable and pleasing;`" and the deceiver says,
"`My way is wit and effectiveness;`" and the foolish jester says,
"`My way is mirth and gladness.`"
So the devil blinds and leads each man in such a
way that he cannot see wherein he is deceived,
but rather walks on and presses forward until he comes to the end,
where the pit is prepared.
This is the broad way in which most men walk,
where man seeks to satisfy the flesh with its affections and lusts.

Thus all evil proceeds from the deceitful heart, where the serpent begets his image.
For from here comes murder, adultery, covetousness, drunkenness, pride, envy, malice,
with all other things that are evil, and which separate man from God.
And in this state no man can please God, nor do any good,
for all his works are brought forth from the strength and
power of darkness which has free reign in the fleshly part,
and in the flesh never ceases to generate lustful desires.
And when man joins with the temptation (which the
serpent offers to the lust that he has begotten),
then sin is conceived; and when sin is conceived and brought forth,
then death comes over man.
Thus it is written, "`sin entered the world, and death through sin.`"^
footnote:[Romans 5:12]

For the wages of sin is death, and as man lives according the flesh, so he dies;
for all his works are corrupt and unclean, and the pure God has no pleasure in them.
_And as long as man walks in the flesh he abides under condemnation;_
the wrath and curse are upon him, and the hand of the Lord is against him.
And whether it be open profaneness, or a profession of godliness,
if it arises from darkness and has its course in the fleshly part of the creation,
it is all condemned and judged by the Spirit.
Yes, he that walks after the flesh,
and satisfies the lust which the serpent has begotten, will at last be overcome by death.
Such a man must die because his deeds are fleshly and carnal.
Thus Paul says, "`death has spread to all men, in that all have sinned;`"^
footnote:[Romans 5:12]
and as long as a man`'s way is in the fleshly part,
and his works are brought forth in the lust of it, so death remains on him,
and he dies the same death as the first man in transgression.
For there is no respect of persons,
but "`he that sins without the law shall perish without the law;
and he that sins under the law shall be judged by the law.`"^
footnote:[Romans 2:12]
So shall every man`'s way and work be proved,
and he will be recompensed according to what he does.
He that sows to the flesh, shall of the flesh reap corruption,
and in this state he cannot inherit incorruption.
Thus the drunkard, the swearer, liar, proud, covetous, boaster, envious, wrathful,
foolish jester, vain talker, fornicator, murderer,
along with every deceitful and hypocritical professor
of godliness without the power of God,
cannot inherit the Kingdom of God, for they are in the unclean nature;
their ways and works are in the flesh.

He "`that lives according to the flesh shall die.`"^
footnote:[Romans 8:13]
He cannot inherit the kingdom of God,
but abides in separation from the God that made him,
and in that uncleanness which cannot approach Him.
Indeed, righteousness and unrighteousness have no fellowship together,
and with a polluted garment man cannot enter into God`'s pure paradise,
nor enjoy His pure presence, but is separated afar off from Him.
Here he is plunged into woeful misery,
into groaning and sighing in the lowest parts of the visible creation,
where the serpent is prince and rules over him.
And so long as anyone lives and walks in the flesh, and brings forth its works,
he remains a degenerated man, at a great distance from God.
In these, the earthly part has grown over them and made a separation,
which burdens the pure seed that is held in bondage under a mixture
of the fallen properties that are all out of order.

Therefore, it is needful that every man consider his ways and works,
and quickly lay it to heart, considering that all have sinned,
and none can be saved in their sin, nor please God in the flesh,
neither can flesh and blood inherit His Kingdom.
For all who live and walk in the flesh remain separated from God,
where His wrath is experienced and His judgments are executed,
without respect of persons.
