== Chapter V. What it is that Convinces Man of Evil

Man, being drawn into disobedience through the subtle working of the prince of darkness,
became a transgressor of the pure power and wisdom of the Creator.
He went out of the good, in which he was created,
and went into the evil by obeying the tempter.
And having eaten of the mixture into which he fell,
the "`imaginations of his heart became evil continually,`"^
footnote:[Genesis 6:5]
and evil wrought more and more to gain dominion over the good;
so that man was deprived of all glory and alienated from the holy Life.
Nevertheless, the Seed of God did retain its own pure, holy quality and property,
without any mixture, and it was not extinguished by the fall of man.
Though man went out from it, and did not abide in it, still the Seed kept its purity,
and the pure Light did shine in man`'s conscience (through the eternal love of God),
to convince him of the evil ways and works into which he had fallen.
The Light shined in darkness, and discovered the deeds of darkness,
and convinced man of the evil of them.

By the light of this Seed, Adam was convinced of his transgression and so hid from God.
By it Cain was convinced he had murdered, and cried out because of his punishment.
By it Saul was convinced of his cruelty, and said to David,
"`You are more righteous than I.`" The light of this
Holy Seed of life shines forth in love,
and is made manifest in the consciences of fallen men,
being freely given of God to seek after man in his fallen state.
Wherever the subtle serpent has drawn the minds of men, and begotten his image,
there the Light searches and shines to convince and reprove man in his own conscience,
so that he cannot hide his secrets and treasures.
For the light shines in darkness, though the darkness does not comprehend it,
and with its pure brightness it discovers the deeds of darkness,
along with the prince of darkness, making manifest his secret workings,
and _letting man see and feel that he is a stranger to God,
and an alien from His pure life, serving a spirit that is at enmity with God._

In this way the love of God has been made manifest by the Light of the Seed of Life,
which through all generations has been the same, and with its pure quality,
has uncovered the enmity of man`'s deceitful heart, and all its deceitful workings.
It has brought hidden things to light, showing unto man how his mind has been used,
and towards what it has been inclined, and after what his heart has lusted.
Whenever lust has prevailed unto evil, the Light has been near to convince man of it,
and to reprove him for it.
And when man has done well,
by the same Light he feels himself to be justified and approved,
and is made to see his acceptance.

Thus the Lord God waits that He may show mercy,
and through all generations His mercy has been made manifest,
that in mercy He might restore the creation to its holy order,
and bring man out from under the power of darkness.
He seeks to set man free from bondage,
that no corruptible thing (into which he has fallen
through disobedience) may remain upon him,
but that it may be taken away and removed,
and that the Lamb (who was slain from the foundation of the world^
footnote:[Revelation 13:8]) may be quickened and raised up in him,
and come into His pure dominion without any spot or blemish.
For He is more pure than to mix with any corruptible thing,
and indeed the corrupted things press upon His tender Life in the heart,
and He bears their weight.
In much patience He suffers under them, the Just for the unjust,
that He may again bring man unto God,
and restore the creation to its pure order where it formerly rested with God,
having its motion in the power and wisdom of God.

This Life within is Christ the holy Seed, with whom the covenant stands sure,
unto whom all the promises are made, and in Him alone they are yes and amen.
And from the beginning,
this Seed has been revealed to bruise the serpent`'s head and to destroy his works.
Throughout all generations it has been at work,
even in the fallen properties of the visible creation,
to seek and find man in all his out-goings and in
his secret walking in the paths of darkness;
for it manifests man`'s evil desires and convinces him in his own conscience
whenever lust reaches forth its hand to seize what is evil.
This it has done in generations past, and this pure property does not change.

Thus it is that man, through the convincement that reaches unto him in the Light,
is made a sensible creature, and in his own conscience he knows he should not do evil,
for he sees the evil in himself before he commits it.
And when the temptation draws him and prevails over him,
he is then able to see that he approaches nearer unto evil.
Therefore all men are left without excuse, for evil is made manifest unto them,
and they are convinced in their own consciences.
And all who run into evil, or are found in any evil, either in thought, word, or deed,
these transgress against the Light which shines forth in love from the holy Seed of Life,
and which discovers and convinces man in his own conscience.

Here man is in the fall, where all the properties of the whole creation are out of order,
and his lustful heart eagerly pursues the things that are evil.
Yet wherever he may run in the fall, or in whatever path the serpent may lead him,
still the Light does discover it, and makes the evil manifest in his own conscience.
And so the drunkard is convinced that his deeds are evil,
and that he abides in the uncleanness of them;
and that which does convince him is the Light in his own conscience,
which is pure without any mixture of evil.
The deceitful man is convinced that he is not just,
and that which convinces him is the Light of Christ, which is just and holy.
The liar is convinced that his deeds are evil,
and he sees it in secret even while the lie yet remains in his breast.
And that which lets him see his lie before it is spoken, and convinces him of it,
is the Light of Christ in his own conscience, which is true, having no deceit in it,
and it is made manifest to destroy all lies, and the father of lies.
Indeed, there is not anything that the serpent has generated,
which is not discovered and shown by the "`true Light
that enlightens every man that comes into the world.`"^
footnote:[John 1:9]

For the serpent has seated himself in the mixture of the earthly corruptible part,
amongst the fallen properties, and there he has his course and his way in the darkness.
There he generates a deceitful heart,
out of which proceeds all manner of evil that defiles the man.
And thus he has generated a body of sin,
and worked through deception in the corruptible properties
to draw man`'s mind out after sin.
Here he also begets love and delight in sin,
provoking lustful desires to eagerly pursue it, which can never be satisfied.
For as man runs in this path of the serpent`'s devising, and follows him in his leading,
and lusts after his temptations, he draws a great burden upon himself,
and comes into much trouble,
and finds that there is something underneath that groans with the weight of those
lusts and sins which the serpent has generated into a body of sin.
For that which groans within is of a contrary nature; it is not corruptible,
but feels itself oppressed and burdened by all corruption.
It is the serpent who has generated corruption from the beginning,
and into it he has drawn man`'s life,
so that the whole creation is put out of its holy order and so travails in pain,
and the whole course of nature is thus set on fire.
Thus man has been deprived of that pure understanding in which he was created,
and in which he first discerned and knew the whole creation
when it stood in the power and wisdom of God.

But although man is so far degenerated, and has lost his original understanding,
and the serpent has drawn him into the fallen properties of the corruptible
part of creation wherein he has become as a beast without understanding,
not knowing the God of power and wisdom, nor the order of His creation; nevertheless,
in this degenerated state (in which man can be said
to be separated and far off from God),
there remains a pure holy Seed that abides within him which,
in its pure light and brightness, reaches unto man`'s deceitful heart.
And with its light and brightness,
this Seed truly uncovers all evil that is generated in the deceitful heart,
and convinces man of the evil, whether in thoughts, words, or deeds.
And when the heart lusts to anger, and anger is kindled in a man`'s breast,
then the light makes this manifest,
and by the light man is convinced that he is engaged in a thing that is evil.
And whatever is generated by the serpent and then
conceived in the deceitful heart of man,
the Light finds it out;
and there is nothing that can stop its passing through
and searching the fallen properties to uncover man,
who has become an evil-worker, and to convince him of all his evil deeds.
For man cannot escape the Light, though he walks in the midst of darkness,
and chooses his way in the dark places of the earth, and treads in the serpent`'s paths,
bringing forth the works of his begetting.
Even here the Light will find him out, and by it man will be convinced,
and the sin will be placed in his own conscience that he may see his evil deeds,
which separate him from God, and keep him alienated from the holy Life.
