[short="Chapter VI -- How Man Stands in a Convinced State"]
== Chapter VI. How Man Stands in a Convinced State, and also the Serpents Working

When a man in his fallen condition is overcome by evil,
so that his deceitful heart brings forth a birth of the serpent`'s begetting,
then the pure Light comes to him in order to convince him,
and lets him see that he is an evil-doer, and that he is ensnared in what is not good.
And when the light has thus exposed and convinced him,
it truly and plainly makes known to him that his way is not right,
nor are his works approved by God,
and that if he goes on without repentance he will perish.
And in this same light man sees that his conscience is defiled,
that there is uncleanness upon him, and that his heart is not upright,
but rather full of deceit.
Most men will acknowledge this in words,
admitting they have a deceitful heart from which many evil things proceed,
and that they are evil-doers and sinful men.
Yes, when the light reaches a man and so far convinces him of evil, even a drunkard,
a liar, and a swearer will make such a confession,
for God leaves every man without excuse.
He knows and sees all evil, and makes it known by the true Light of Christ,
the Seed of God,
which sees through all the properties of the visible
creation and makes manifest every way of darkness.

And this Light has been within man ever since the breath of Life was breathed into him.
And though the fall came upon man by subtlety,
and he fell into the mixture of properties in the visible creation,
yet the Light itself which was breathed in the life, whereby man became a living soul,
was not extinguished by his fall,
neither was its property changed when man went into the mixture.
No, the Light retained its pure and holy nature,
though man was enticed away from it and entered into the evil,
and so began to abide in death.
This pure Light of Life has throughout all generations been the same,
and by its searching quality has uncovered all evil that man has or commits.
It has never changed in its property or quality, but has continued pure, holy, righteous,
and meek, as it is at this day;
but man in the fall has become something that is not of its nature,
but rather contrary to it, so that the light discovers, testifies against,
and reproves all the devil`'s works which he has begotten in man since the beginning.
And though the serpent has gained dominion over man, and begets his evil deeds in him,
even so the Light continues to uncover these things, and lets man`'s conscience see them;
for the light is made manifest in the conscience in order to bruise
the serpent`'s head and to destroy his work in man.

This testimony is sure, though the subtlety cannot receive it,
and all who ever became acquainted with the holy Seed of Life,
never testified of another thing, nor preached another gospel;
so that the gospel of the Seed preached to Abraham
has been and is the same throughout all generations.
For the holy Seed does not cease from searching after
man who has fallen into the mixture of properties,
and there it strives with him by convincing and reproving,
that man may not abide in death but arise and follow it, and come to inherit life.
And this is the love of God, which was, and is, and is to come;
who desires that none should perish, but rather that all should turn and live.
And though His love is freely made manifest, and finds man in his disorder,
walking according to his disorderly and unruly affections which the serpent has begotten,
yet man (for the most part) does not receive the offer of God`'s love,
nor does he turn at the reproof of the Light.
Instead he loves his evil deeds more than he loves the Light,
and will not come to the Life,
but is held by the serpent`'s subtlety in the mixture of the fallen properties,
and there he delights more in evil than in good.
And for this the Light condemns him,
and the evil-doer cannot escape the convincement of the Light for his evil deeds,
but whatever it is that he lusts after, and finds his life in,
that the Light makes manifest, no matter how secret, for no man can hide from the Light.
And though the serpent begets many evil things,
and provokes man more and more towards an evil conscience,
and captures man`'s mind therein,
yet the Light does not cease at times to bear testimony against man in his evil,
and to convince him of his evil deeds.

In this way man stands in an acknowledgement of his sin and evil,
but not turning to the Light when he is convinced by it and sees his evil,
he continues to abide in the evil.
And the serpent still having dominion over him,
persuades his mind that this Light that convinces is not sufficient to save him.
And he thereby generates unbelief, and draws the mind away from obeying the light,
or waiting in it to know the operation of its power.
And man, heeding the serpent`'s counsel, is drawn further away from the Light,
and will not believe that it is able to save him,
nor will he turn to the light when he is convinced by it,
but rather calls it a "`natural light`" or a "`natural conscience`" or "`the
most tender part of a natural man,`" not believing that it comes from God,
nor that it can save or give life when obeyed.
And many are told that this is not the work of the Redeemer, or Mediator, or Intercessor,
for those names (they say) belong only the man Christ Jesus who died at Jerusalem,
and men must only put faith in what has already been done for them,
and then their sins shall not be imputed,
even if they live in them and continue to commit them.

In this way the serpent has deceived many people,
begetting unbelief in the Light that shines in their own conscience
showing them their sin and convincing them of it,
and also begetting an imaginary faith that they will
be saved by the Christ who died at Jerusalem,
though they continue to abide in their sins.
Thus it is that sin is _made manifest_ in many, but it is not _destroyed,_
and the serpent persuades man that it cannot be otherwise while he bears a natural body.
"`For,`" says the serpent, "`man`'s nature is prone to sin,
and none can be free from it until their body is laid in the earth.`"
Thus the serpent works unbelief in the Light of Christ,
and begets a false faith in a merely outward Christ, but not in His work within man.
And so many believe that, though here in this world they sin out their time,
yet hereafter they shall be saved.
And thus not obeying Christ`'s light, these do not come to know His life and virtue,
nor His salvation, mediation and intercession,
but abide in the mixture of fallen properties without experiencing
any change wrought in them by the power of Christ.
Here men stand convinced by the light, seeing things that are evil,
but because they do not believe in the Light,
they still abide in the evil and are not truly converted.
