[short="Chapter VII -- How Man Stands in a Converted State"]
== Chapter VII. How Man Stands in a Converted State, and also the Serpent`'s Working

The pure creation is thus in sore travail and pain
through the disorder of the fallen properties,
where the serpent has seated himself and exalted himself over all that is called God.
Here he keeps man in a state of alienation from the Life of God,
where the shadow of death is over him, and sore grief and pain are upon him,
which heavily oppresses him and makes him go about mourning day by day,
so that he at times begins to consider his state and condition.
And as he ponders these things in his mind,
the pure Light shines forth in his conscience and shows
him at what a distance he is from the pure God,
and how he is alienated from His Life,
and what a great body of corruption there is within
him that causes his separation from God.
And when this is made manifest unto him,
he is struck with the sense of his miserable condition,
and is brought into a state of waiting to see if
he can find anything to help or relieve him.
He then at times he feels something within himself that cries out after God,
from whom he has been separated by the body of sin,
and an enquiry emerges about the way to come unto Him,
and how to be freed from those things that separate him from God.
And as this earnest enquiry continues, the Light shines forth more and more,
and true discoveries are made.
For in the light man begins to appear unto himself to be exceedingly sinful,
and calls into question many things that he has lived in,
seeing them to be of an unclean nature.
And so he begins to dislike such things,
and can no more delight in them as he has done in time past, but starts to abhor them,
and to wait in the Light which made them manifest
to see if he may be preserved from them;
for he now sees that they are evil, and that they defile him,
and are a heavy burden and a painful weight upon him.
And so by paying attention to the light, and obeying whatever it makes manifest,
he receives a measure of power against these things, and gains some victory over them.

Now man in this state may still have little acquaintance with the Light, and yet,
as he is faithful in turning to it,
according to the manifestation of it and the knowledge that comes by it,
turning from evil unto the light, thus far a true conversion is wrought.
In this way man ceases from much vanity that he has lived in,
and departs from the unclean paths of profaneness,
and those things that were once lovely to him now become loathsome.
He thereby ceases from drunkenness,
and the excess of food and drink which he has become accustomed to,
and from all lying and swearing and fashionable apparel,
in which he has lived and delighted.
And that which works this change, and brings man into moderation,
is the pure Light of the holy Seed of Christ,
which has never consented nor found pleasure in man
when he is engaged in things that are evil,
but has always endeavored to convince man of the evil.
And as he obeys the Light of Christ, a cord of love is cast around him to draw him,
and the Lord continues to work man`'s conversion.

Now many have come into this condition, being convinced by the Light,
and also converted from many evil and profane things,
and yet have never been perfectly loosed from the bonds of death,
but have been kept still in the house of bondage.
For the serpent works deceitfully to keep man in a form of religious
profession where he walks like a sober and moderate man,
and reforms his evil ways, and makes a fair show,
and yet begins to neglect the Light in his conscience,
drawing his contentment from what he professes with words.
With this false image that the serpent generates in the imagination he has deceived many,
and caused them to err from the right way,
drawing them off from the Light after they have been convinced of it,
and turned by it from many evil things.
And such as these often become the greatest enemies to the Light,
for it is hard to renew one who has once been enlightened,
and for a time has been turned, and has known a beginning of the work of God,
but afterwards turns from it.
These indeed become hardened,
and so quench and stop the power before they are
truly regenerated or experience the new birth.
Yes, the serpent has brought forth many false births and likenesses,
whose deformity and impurity has marred the beauty of the true heavenly birth.
And from here many religions and groups have risen up,
denying many things that are evil and profane, and professing the Scriptures,
and with this fair show multitudes are satisfied.

Yet the Light of Christ in man`'s conscience continues to
search after those who are in this professing state;
for though they do not walk as drunkards or swearers,
yet the light shows them to be will-worshippers and man-pleasers,
and it testifies against their double-mindedness, instability and hypocrisy.
For though there appears to be a great difference
between outright profaneness and a show of godliness,
yet these are generated from the same womb,
and receive their nourishment from the mixture of
fallen properties which abide in chaos and confusion,
and have Mystery Babylon as their mother.
So that open profaneness and a profession of godliness without the power,
are both defiled, and both are condemned by that Light which is pure.

This is the lamentable state of many;
and many have come thus far and could never get further,
for they have taken up their rest in a formal profession
where there is neither relief nor satisfaction,
and have not endured the fight of affliction after having been enlightened,
but have departed from the narrow gate which leads to the pool of healing.
No, they have not patiently waited until He has come
and given them power to pick up their mat and walk,
but have wandered away (though weak and lame) into the way that is broad,
evading the cross and healing themselves with false liberty.

Yet in this foreign land there is still something
within man that longs after its native country,
where there is no corruptible mixture,
and the Light continues to search man`'s deceitful heart,
from which proceed both profaneness and a profession of godliness.
And by the shining of the Light, the hearts of some do open,
and come to see that they are not upright before the Lord,
nor does their heart align with their outward profession,
but feigned humility and hypocrisy lodge within,
for which they are smitten and corrected by the Lord.
Then these find that they are indeed miserable, weak, and corrupt,
and see that both their righteousness and their filthiness
arise out of the mixture of fallen properties,
and they are sensible of the correcting hand of the Lord.
And though they have denied much profaneness, and made a great profession of godliness,
they perceive that they are daily sucking from a dry fountain.

And if these will begin to mind the Light and wait in it,
it arises to pull down their strongholds, and lay waste their walled cities,
bringing to nothing the glory of their fair show, staining their pride,
and showing them that outward observances cannot bring contentment within.
And so the Light pursues them, and lays many stripes upon them,
and sets their sins in order before them, and lets them see their great body of sin,
for which they cry out to the Lord in their misery, "`Who shall deliver me?`"
And they become sensible of their own insufficiency,
and that without Christ they can do nothing,
and that all outward things are but miserable comforters
with no power to help them in time of need.

Now if these continue to incline to the light that shines within them,
and are diligent in hearkening, obeying, and turning to it,
minding its reproofs and waiting to feel its movements,
then it does convince them of even more evil.
And as they yield themselves to obey,
and to deny that which they are convinced to be evil,
_then the Light will also destroy the evil, taking it away,_
and hereby they come to be satisfied that it is indeed the
truth of God and the way wherein they should walk.
And the more they wait to feel its drawings, and turn their faces towards it,
_it begets a willingness to give up to follow it, and so here men are not only convinced,
but also converted,_
and turned away both from common profaneness and from every false show of godliness,
following the light and denying all evil that the Light discovers.
For in the leadings of the Light,
a man is kept under the cross to his own corruptible will,
and learns to walk in the narrow way,
feeling something of the Lord`'s power working within to crucify
and remove many fleshly lusts that have waged war against his soul,
bringing him into a measure of ease,
and taking off much weight that had lay heavy upon him and been a sore burden to him.

And when the Light has thus found place in a man, and man has turned to it,
so that he can no longer abide in either profaneness nor an outward show of godliness,
but presses after the Light to wholly come out of the mixture
of fallen properties into the holy order of the pure creation,
then the serpent does strive in his subtlety to hold man in some measure of mixture,
that he may at least in some things keep dominion over him,
and not let him be wholly free.
And here, though they are convinced of many truths, and have denied many evils,
yet they often get stuck in the birth and do not
come to feel a true freedom worked within,
but rather a travail continues that cries out for a day of deliverance.
Yes, the serpent has deceived many who have been both converted and convinced,
and have had true openings and clear discoveries in the Light; but not being watchful,
he has beguiled many a man (just as he beguiled Eve), by tempting with the same fruit,
and prevailing over them by drawing their minds to reach in their own
eagerness to satisfy a human desire for the knowledge of God`'s truth.
This shuts the womb upon the Life that is being formed within,
for men in this condition will flee the judgments of God, deny the cross,
and grow up in false liberties that give birth to bondage.
And though they confess and profess the truth,
yet the Seed lies in bondage under their puffed-up
mind that the serpent has filled with knowledge,
and under a false birth that he has brought forth.
Thus their neck becomes progressively stiff, their heart hard,
and they will not bow unto the Lord nor be subject to His power.

For though a man may have seen Truth in the Light,
yet the carnal mind becoming filled with the knowledge of this,
shoots its roots into the earthly part,
and the earthly begins to grow and spread forth its branches in a fair show of godliness.
And though this earthly body that has been generated
and nourished in the mixture of the fallen properties,
and has a tincture of the Truth upon it from the Light (just
as lead may be thinly covered with pure gold),
and appears exceedingly glorious, yet it is not the glory of the only begotten Son.
The old serpent then labors to nourish this birth, that it may grow in strength,
and become like a tall and strong man, sprung up in height like the cedars of Lebanon,
and in knowledge like the oaks in Bashan.
And under this high and mighty growth in knowledge,
the little breathing Seed is strangled, burdened, and oppressed,
still striving in meekness and humility to bring
down the tall cedars and to bend the strong oaks.
But the tall cedars refuse to lose their glory, and the oaks to part with their strength,
but rather stand stoutly and stubbornly resisting
the tender Seed and casting off the word of reproof.
For the tall cedar says, "`Who shall rule over me?`"
And the stubborn oak says, "`Who shall cause me to bow?`"
And so they trample the innocent Seed as a thing of no esteem,
and remain in the mixture where a clean separation is not made,
and where the dross and tin will not remain in the furnace,
nor abide the Day of His coming.
For the serpent has ever worked secretly against the Seed of Life,
which is made manifest to bruise his head and destroy his work.
And though a man may have followed the Light in self-denial
and in the daily cross to many fashions,
customs, and traditions,
yet the Seed may still be closed up in the womb for lack of deliverance.

But the true new birth or regeneration proceeds from the holy womb,
and is brought forth in the furnace without any mixture of the earthly part.
And where it is born, it changes the entire man throughout,
and perfectly redeems him out of the world,
being nourished by the breasts of the holy Life,
and so grows in the Life`'s pure nature and power,
which makes war and overcomes the serpent and his power.

Therefore, let all the tall cedars and strong oaks consider these things,
and stoop low and bow, for they must fall and be broken,
and the innocent Seed must reign over all because it is pure and without mixture.
And also let all consider who have had a taste of the true power,
and have known something of its work,
but have again returned into folly or have flown up into the air,
and now plead their fleshly liberty as a thing that is natural to the visible creation,
and dare say, that though they live in such liberty it does not defile the inner man,
nor do they feel any reproof for their fleshly and carnal deeds,
but stand justified before the Lord in their inner man; I say,
let all such as these know, as from the Lord,
that they are like birds of the air that took their flight in winter,
and the hand of the Lord will bring them down.
And let the proud and arrogant consider, who dare say that all their works,
whether they are good or evil, are wrought in God, and whatever they do is His doing,
though it be evil; let these know that they are in the devilish and ranting spirit,
making merry over the pure and innocent Life.
And let such as these sink down and hereby know, yes, as from the Lord,
that their life is appointed for death, and their works for judgment;
for the holy Seed shall arise and bruise the serpent`'s head,
and the serpent cannot save it with all his twisting,
nor keep his deceitful works away from the judgement of God;
but all that he has built must be defaced, and all of his works be destroyed.
