== Chapter X. The Way and Works of Man in the New Creation

By this Restoration a man is changed, and becomes a new man in Christ,
and his way and all his works are new.
He becomes a well-doer, and is accepted of God in Christ the Beloved.
Here man finds the new and living Way, which makes him a new and living man,
and leads him unto the living God.
This is the highway of holiness where clean feet walk,
and the man that orders his way in it is in the way of peace,
and is led into the green pastures of everlasting refreshment,
and walks continually by pleasant streams,
and his journey is along that river that makes glad the whole city of God.
His life is bound up in the holy Life of the immortal Seed,
and he moves with it wherever it goes, and will not move but by its order,
and in its strength.
And as man keeps in close communion with the Seed,
he is strengthened to run the way of every commandment,
and there is no feebleness in his loins,
but perfect strength keeping in the motion of the holy Seed,
which carries him upon eagles wings, running and not growing weary,
walking and not growing faint.
His way becomes holy, his works are "`holiness unto the Lord`",
and he is created anew in Christ Jesus to walk in them.
Yes, such a man is no more his own, but is at the Lord`'s disposal,
truly serving his God in righteousness and true holiness.
He no more thinks his own thoughts, nor speaks his own words, nor works his own works,
but is moved and acted upon in the power and wisdom of the holy Seed,
of which he is born and made a new creature.

Thus man is changed, and is made a holy man, a righteous man, a godly man, sober, chaste,
gentle, meek, patient, loving, kind, good, lowly, tender-hearted, forbearing,
and long-suffering, and in all things he walks according to the order of the holy Life,
into which he is born, and in which he lives and moves.
Indeed he becomes a lamb in the Lamb`'s nature,
and is beautiful in the brightness and holiness of the Pearl`'s glory.
And thus is man translated and changed,
through the effectual Working of God`'s mighty power.
With a new heart he glorifies his Maker,
and is sincere and upright in his heart before God.
The Lord God takes pleasure in him, and approves of his way and his work,
and justifies him therein.
There is then no condemnation upon him,
nor any wrath or curse that goes forth against him, or falls upon him,
but he dwells in the eternal love, and the love dwells in him, and he bears its image,
clear from all defilement, spot, or blemish.
Then does the glory shine out of the Precious Pearl,
and the scepter of the Lamb does bear its sway, and upon His throne He is exalted.
He clothes his saints with pure righteousness,
and sets crowns of pure gold upon their heads.
And so they rest with Him in the holy land, and move in the holy order of life,
singing the songs of holiness and praise within the gates of the new Jerusalem.
For the Lamb fills them with joy and gladness,
and with a new heart and a new spirit that sound forth His name,
and they never cease to give glory, honor, thanksgiving, praise, and hallelujahs,
unto Him that sits upon the throne.
